[package]
name = "caliptra-emu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitfield = "0.13.2"
clap = { version = "3.2.14", features = ["derive"] }
lazy_static = "1.4.0"
