[package]
name = "caliptra-lib"
version = "0.1.0"
edition = "2021"

[lib]
test = false
doctest = false

[dependencies]
tock-registers = { git = "https://github.com/tock/tock.git" }
caliptra-registers = { path = "../registers" }
ureg = { path = "../ureg" }
cfg-if = "1.0.0"

[features]
emu = []

[profile.release]
opt-level = "s"
lto = true
panic = "abort"

[profile.dev]
opt-level = 2
lto = true
panic = "abort"

[[test]]
name = "sha256"
path = "tests/sha256_tests.rs"
harness = false

[[test]]
name = "sha384"
path = "tests/sha384_tests.rs"
harness = false

[[test]]
name = "hmac384"
path = "tests/hmac384_tests.rs"
harness = false

[[test]]
name = "doe"
path = "tests/doe_tests.rs"
harness = false

[[test]]
name = "ecc384"
path = "tests/ecc384_tests.rs"
harness = false

[[test]]
name = "mailbox"
path = "tests/mailbox_tests.rs"
harness = false
