[package]
name = "compliance-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.14", default-features = false, features = ["std"] }
getrandom = "0.2"
caliptra-emu-lib = { path = "../lib" }