# Licensed under the Apache-2.0 license

[package]
name = "caliptra-hw-model-c-binding"
version = "0.1.0"
edition = "2021"

[dependencies]
caliptra-hw-model = { path = "../" }
caliptra-emu-types = { path = "../../sw-emulator/lib/types" }
caliptra-emu-bus = { path = "../../sw-emulator/lib/bus" }
caliptra-builder = { path = "../../builder" }

[lib]
crate-type = ["staticlib"]

[features]
verilator = ["caliptra-hw-model/verilator"]

[[bin]]
name = "image"
path = "bin/image_gen.rs"